LNST-project/lnst

- lnst/Common/LoggingHandler.py
- lnst/Common/Logs.py
- lnst/Controller/Controller.py
- lnst/Controller/Recipe.py
Description:
Added lists of log messages from controller and all the slaves to exported `.lrc` files.
Exported `.lrc` files could be imported using `lnst.Controller.Recipe.import_recipe_run()` function.
After that logs could be found in `RecipeRun.log_list["controller"]` and `RecipeRun.log_list[SLAVE_ID]` lists.
Example:
```
from lnst.Controller.Recipe import import_recipe_run
from runner import HelloWorldRecipe
run = import_recipe_run("HelloWorldRecipe-run-2021-06-23_22:07:23.lrc")
print(run.log_list)
>>> {"controller": [<LogRecord: root, 20, /home/sdobron/rh/forked/lnst/lnst/Controller/SlavePoolManager.py, 49, "Checking machine pool availability.">, ...]
"machine1": [<LogRecord: root, 20, /root/lnst/lnst/Slave/NetTestSlave.py, 410, "Performing machine cleanup.">, ...]}
```
Reviews: …
> Exporting controller&slaves logs to .lrc files

- lnst/Recipes/ENRT/BaseEnrtRecipe.py
Tests:
```
$ ~/.local/bin/poetry run job-generator -t kernel-minimal,production -d RHEL-8.4.0 --build-brew-nvr kernel-4.18.0-305.el8 -p Low --lnst-git-url https://github.com/jtluka/lnst.git --lnst-git-branch add-skip-perf-evaluation-parameter -m machines-lnst-netdev-all > /tmp/j.xml
$ bkr job-submit /tmp/j.xml 
Submitted: ['J:5594556']
```
Another job with `skip_perf_evaluation=True`: J:5594559
> Recipes.ENRT.BaseEnrtRecipe: add skip_perf_evaluation parameter

- lnst/Recipes/ENRT/SimpleMacsecRecipe.py
After a bunch of refactoring commits in history this should now be a
redundant method. At the same time the recent refactoring of the
FlowMeasurementGenerator method this code is broken as the semantics of
the `self.params.net_perf_tool` parameter have changed.
Removing this method should resolve the issue and simplify the code.
Signed-off-by: Ondrej Lichtner <olichtne@redhat.com>
> SimpleMacsecRecipe: remove generate_perf_configurations method

- install/lnst-slave.service
- lnst/__init__.py
- pyproject.toml
Description:
Removing top level init that was redundant and not used.
Updating the pyproject.toml, bumping project
version to 16 and python version to 3.6 and higher
to speed up installation.
Whenever LNST was installed as a dependent project
poetry was unable to stitch together multiple
packages and their modules.
Easiest solution is to update paths accordingly [0].
[0] - https://packaging.python.org/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages
Tests:
J:5614799
Reviews: 
@olichtne @jtluka
> lnst: add pkgutil style namespace packages

- lnst/RecipeCommon/Perf/Evaluators/NonzeroFlowEvaluator.py
- lnst/RecipeCommon/Perf/Measurements/BaseFlowMeasurement.py
Description:  
Replaced hardcoded result pass with evaluating in `BaseFlowMeasurement._report_flow_results()` to correctly evaluating flows with invalid duration.  
Fixed evaluating `inf` as valid passed result in `NonzeroFlowEvaluator.evaluate_results()`.
Reviews:  
@Axonis @olichtne @jtluka
> Evaluating flows in BaseFlowMeasurement and fixed evaluating infinity in NonzeroFlowEvaluator

- lnst/Recipes/ENRT/GreTunnelOverVlanRecipe.py
- lnst/Recipes/ENRT/VirtualBridgeVlanInGuestMirroredRecipe.py
- lnst/Recipes/ENRT/VirtualBridgeVlanInGuestRecipe.py
- lnst/Recipes/ENRT/VirtualBridgeVlanInHostMirroredRecipe.py
- lnst/Recipes/ENRT/VirtualBridgeVlanInHostRecipe.py
- lnst/Recipes/ENRT/VirtualBridgeVlansOverBondRecipe.py
- lnst/Recipes/ENRT/VirtualOvsBridgeVlanInGuestMirroredRecipe.py
- lnst/Recipes/ENRT/VirtualOvsBridgeVlanInGuestRecipe.py
- lnst/Recipes/ENRT/VirtualOvsBridgeVlanInHostMirroredRecipe.py
- lnst/Recipes/ENRT/VirtualOvsBridgeVlanInHostRecipe.py
- lnst/Recipes/ENRT/VirtualOvsBridgeVlansOverBondRecipe.py
- lnst/Recipes/ENRT/VlansOverBondRecipe.py
- lnst/Recipes/ENRT/VlansOverTeamRecipe.py
- lnst/Recipes/ENRT/VlansRecipe.py
Some switches are configured to allow only a small number of VLAN IDs (such as in klab.bos lab).
Allow passing an optional argument vlan_id/vlan_ids to specify what VLAN tags to use in the tests.
Note: only tested VlansRecipe
> Add optional parameters for VLAN IDs

- lnst/Tests/Iperf.py
Iperf running as server may exit with return code 0 and return an empty json.
This usually happens when the iperf running as client cannot complete
the test, for example when running a UDP stream test with multiple
streams on debug kernel.
If the server's json output cannot be parsed the test module should
return False status.
Signed-off-by: Jan Tluka <jtluka@redhat.com>
> Tests/Iperf: fix parsing of empty json output

- lnst/Controller/Controller.py
- lnst/Controller/Recipe.py
I noticed that the `overall_result` property is `True` even if an exception is raised during recipe run.
> Include an exception in RecipeRun overall_result evaluation

- lnst/Recipes/ENRT/BaseEnrtRecipe.py
Description:
With introduction of new parameter `perf_evaluation_strategy` there is a logical bug in the conditional 
of `BaseCPUMeasurement` evaluator registration. It is being evaluated as follows in default scenario:
```
parameter is "nonzero" = 0
OR
"none" = 1
which results into 1, removing the CPU perf evaluator
```
To fix this logical bug `self.params.perf_evaluation_strategy` is checking whether its string value exists in the given list instead.
Test: J:6280045
Reviews: @olichtne @jtluka
> Recipes.ENRT.BaseEnrtRecipe: fix BaseCPUMeasurement conditional

- lnst/Recipes/ENRT/GeneveLwtTunnelRecipe.py
- lnst/Recipes/ENRT/VxlanLwtTunnelRecipe.py
Description:
Internal need requires us to run performance tests through VXLAN and GENEVE tunnels.
To achieve this `generate_perf_endpouints` methods has been added which triggers the whole hierarchy of performance benchmarks.
Just a note to keep in mind is that when user wants to run pure functional test he has to specify empty `perf_tests` list, instead of being null. If the list would not exist in parameters default value of all `perf_tests` would be used, which results in running all available streams to us. 
Tests: 
J:6377886
The first test-runner has `perf_tests=[]`
While second one has `perf_tests=['tcp_stream']`
Reviews: @olichtne @jtluka
> Add performance testing to functional tunnel recipes

- .github/workflows/ci-test.yml
- container_files/Dockerfile
- container_files/install.sh
- pyproject.toml
Description:
Updating python version being used in LNST.
Decision to do so, was made based on the fact, that newer poetry installer requires python 3.7 and higher, thus giving us an opportunity to update the LNST version with it as well.
Test:
J:6443576
Reviews: @jtluka @olichtne
> Update LNST to use python 3.9

- container_files/Dockerfile
- lnst/Common/Parameters.py
- lnst/Controller/Machine.py
- lnst/Controller/Namespace.py
- lnst/RecipeCommon/Perf/Measurements/BaseMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/LinuxPerfMeasurement.py
- lnst/Recipes/ENRT/BaremetalEnrtRecipe.py
- lnst/Recipes/ENRT/BaseEnrtRecipe.py
- lnst/Recipes/ENRT/MeasurementGenerators/LinuxPerfMeasurementGenerator.py
- lnst/Tests/LinuxPerf.py
Runs `perf record` on all Agents on an interrupt-receiveing CPU and on a CPU where `iperf` is running. All collected data is then copied to Controller.
> Implement performance analysis with Linux Perf tool

- .readthedocs.yaml
By merging the LinuxPerfMeasurement* bits the build of docs on readthedocs [broke](https://readthedocs.org/projects/lnst/builds/16801479/). This is due to python3.7 used for building the docs that is incompatible with type hinting that is present in the LinuxPerfMeasurement* bits.
This patch adds .readthedocs.yml that specifies python3.9 as requirement to build the docs.
I still need to test this as I'm not sure what other bits I need to include in the file.
> docs: specify python3.9 as requirement for readthedocs

- lnst/Controller/ContainerPoolManager.py
- lnst/Controller/VirtDomainCtl.py
- lnst/Devices/VirtNetCtl.py
- lnst/RecipeCommon/LibvirtControl.py
This is a proposal draft to make libvirt into an optional runtime dependency instead of a hard install dependency.
It is typically not used in many/most of our test recipes and having it as a hard dependency can make the experience of setting up lnst a little bothersome.
The draft status is because I haven't tested these changes yet.
> Optional libvirt

- lnst/Recipes/ENRT/MeasurementGenerators/LinuxPerfMeasurementGenerator.py
When 'yield' is used in python it automatically changes the
function/method into a generator. This is regardless of if the yield is
reached or not - this is decided when the function is parsed, not during
runtime.
At the same time, the 'return' statement works differently in a
generator. The return statement raises the 'StopIteration' exception
that is used by loops etc. to detect that the generation has stopped. If
'return' is used with a value, this value is provided to the exception
object:
`return val` is sort of equivalent to `raise StopIteration(val)`
However, when we write:
for i in generator:
The `StopIteration(val)` simply exits the loop, the `val` itself isn't
assigned to `i` to start one more iteration of the loop.
Because of this the old code of the …
> ENRT.LinuxPerfMeasurementGenerator: fix generator return implementation

- lnst/Tests/TestPMD.py
The -w (whitelist) argument has been deprecated and removed since DPDK
version 21.11 [1] and is instead replaced by the -a (allowlist)
argument.
[1] https://doc.dpdk.org/guides/rel_notes/release_21_11.html?highlight=whitelist
Signed-off-by: Ondrej Lichtner <olichtne@redhat.com>
> Tests.TestPMD: change -w to -a argument

- docs/source/extensions.rst
- lnst/RecipeCommon/Perf/Measurements/BaseFlowMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/BaseMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/IperfFlowMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/NeperFlowMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/TRexFlowMeasurement.py
- lnst/RecipeCommon/Perf/Recipe.py
- lnst/RecipeCommon/Perf/Results.py
- lnst/Recipes/ENRT/MeasurementGenerators/FlowMeasurementGenerator.py
- lnst/Tests/Iperf.py
- lnst/Tests/Neper.py
* Fixed slicing intervals (`time_slice()`):
Condition used in slicing intervals allows to slice interval to interval with duration of 0. Interval may not be sliced also for cases, when `end` of new interval is equal to interval's start - it would create an interval [1, 1] instead of [1, 1).
* Added `perf_warmup_duration` parameter for recipes, that uses `Iperf`. It represents warmup and warmdown period, so iperf will measure for `perf_duration + perf_warmup_duration * 2 seconds`, the default value is `0`.
* Trimming results based on latest start of measurement and earliest end of measurements in SINGLE result has been replaced by trimming results by latest measurement. So for example, if there is a list of results `[StatCPUMeasurementResults, StatCPUMeasurementResults, …
> Trimming measurements results

- lnst/RecipeCommon/Perf/Evaluators/BaselineFlowAverageEvaluator.py
Description:  
When an improvement is detected, the formatting simply overwrote the
comparison line completely with "IMPROVEMENT:" instead of prepending
this to the line text like for the other cases.
Tests:  
standard automated tests suffice for this. Will proceed in a hotfix manner for this - if tests pass i'll continue with merge.
Reviews:  
not necessary if tests pass.
Closes: #
> Perf.BaselineFlowAverageEvaluator: fix result text formatting

- lnst/RecipeCommon/Perf/Measurements/LinuxPerfMeasurement.py
- lnst/Recipes/ENRT/MeasurementGenerators/LinuxPerfMeasurementGenerator.py
Description:  
If dev_intr_cpu and perf_tool_cpu contain the same cpus the LinuxPerf measurement would run perf profiler on these cpus twice, also writing to the same file at the same time, corrupting the data.
The two lists need to be aggregated and remove duplicates to avoid the conflict.
Fixes #255
Tests:  
RH internal job ids: ~~J:7083780~~ ~~J:7083775~~ J:7108529 (no override) J:7108533 (override)
Reviews:  
@olichtne @Kuba314 
Closes: #255
> Recipes/BaremetalEnrtRecipe: avoid duplication of perf profiled cpus

- lnst/Controller/RunSummaryFormatter.py
- lnst/RecipeCommon/Perf/Evaluators/BaselineCPUAverageEvaluator.py
- lnst/RecipeCommon/Perf/Evaluators/BaselineEvaluator.py
- lnst/RecipeCommon/Perf/Evaluators/BaselineFlowAverageEvaluator.py
Description:  
Replaced "per type" thresholds support with "per metric" thresholds. BaselineEvaluators now requires `dict` in following format:
`{"[RESULT_INDEX]_[METRIC_NAME]"}`:
* `[RESULT_INDEX]` is index of measurement result in `BaseRecipe.current_run` list. This index is used to distinguish same type measurement because those measurements have same name.
* `[METRIC_NAME]` is name of metric, it usually comes from `Evaluator._metrics_to_evaluate`
For example:
`throughput_avg_threshold=18.05;cpu_avg_threshold=15.08` recipe parameters needs to be changed to:
```json
"thresholds": {
"189_generator_results": 18.05,
"189_generator_cpu_stats": 15.08,
"189_receiver_results": 18.05,
"189_receiver_cpu_stats": 15.08,
"182_host1": 15.08,
"183_host2": 15.08,
"190_host1": 1.5
}
```
As replacing …
> Per metric thresholds

- lnst/Recipes/ENRT/IpsecEspAeadRecipe.py
Description:  
Since IpsecEspAeadRecipe overrides generate_flow_combinations, it also needs to include the perf_warmup_duration parameter value when instantiating PerfFlow.
Tests:  
Internal job id 7228965. I had to use a different branch to not use individual metric evaluation, https://github.com/jtluka/lnst/tree/fix-ipsec-warmup-remove-individual-thresholds
Reviews:  
@olichtne @enhaut
> Recipes/ENRT/IpsecEspAeadRecipe: include perf_warmup_duration parameter

- lnst/Agent/InterfaceManager.py
- lnst/Controller/Host.py
- lnst/Controller/Machine.py
- lnst/Controller/Namespace.py
- lnst/Recipes/ENRT/SRIOVNetnsBridgeRecipe.py
- lnst/Recipes/ENRT/SRIOVNetnsOvSRecipe.py
- lnst/Recipes/ENRT/__init__.py
Description:
Adding new SR-IOV recipe with a single VF placed in the network namespace to mimic the container behaviour. 
There are changes to Controller.Machine and Host, as well as Agent.InterfaceManager to handle the new scenario,
where we are remapping the device of the same class just with changed network namespace.
To actually remap the VF device, we cannot find it by the MAC address, as that is randomly generated, so there is a new method for Machine to locate the device by its interface name, which is consistent.
Test:
EL8 - 7284398
EL9 - 7284270
Reviews: @olichtne @jtluka
> Simple SR-IOV Network namespace OvS and Linux bridge recipe

- lnst/Controller/Recipe.py
- lnst/RecipeCommon/Perf/Evaluators/BaselineCPUAverageEvaluator.py
- lnst/RecipeCommon/Perf/Evaluators/BaselineEvaluator.py
- lnst/RecipeCommon/Perf/Evaluators/BaselineFlowAverageEvaluator.py
- lnst/Recipes/ENRT/ConfigMixins/DevInterruptHWConfigMixin.py
Description:  
Having access to the evaluation data as part of the created final Result object can be very helpful for post run analysis and is difficult to find without this direct link.
As the data is already present somewhere in the lrc file this shouldn't add any overhead except a simple object link to one additional place.
I am also considering defining a custom `class BaselineComparisonResult(Result)` which would be used here instead which could make the filtering in analysis tools even easier because we could simply do:
`comparison_results = [i for i in lrc.results if isinstance(i, BaselineComparisonResult)]`
What do you guys think?
I've had this prepared for quite a while but I think I really require this now to implement the inclusion of analysis data into dashboard - some of the …
> RecipeCommon.Perf.BaselineEvaluator: add data to result object

- lnst/Common/Utils.py
`command` is POSIX compatible and also is usually a shell built-in. `which` is a program that might not be installed on the machine.
Tested just the `is_installed()` function. It works as expected.
@jtluka @enhaut
> Common.Utils: Use command instead of which for is_installed check

- lnst/Common/Utils.py
- pyproject.toml
Description:  
`pgrep` is not installed on all distros by default. We better specify a python dependency than silently require `pgrep` to be installed.
Tests:  
Function successfully checks whether a process with a certain name is running.
Reviews:  
> Common.Utils: Use psutil when searching for running processes

- lnst/Recipes/ENRT/ConfigMixins/OffloadSubConfigMixin.py
This allows user to specify empty value for `offload_combinations` parameter for ENRT recipes to skip NIC offload configuration (run with default NIC setting) when running performance tests. This was not possible before.
Ran SimpleNetworkRecipe with empty set, one and two offload configurations. Tests ran fine.
> Enable empty offloads

- docs/source/conf.py
After the recent change of dependencies we've started using `psutil`
module in our lnst.Common.Utils module. This leads to an undefined
import when building the docs with just the `docs/requirements.txt`
dependencies and creates a lot of empty pages.
Adding the dependency to mock imports fixes the issue as we don't
actually need this when building the documentation.
local build of the docs now completes without `missing psutils` errors
@jtluka 
Closes: #
> docs/requirements.txt: add psutil

- container_files/Dockerfile
This updates the container's base image to Fedora 36. Also tcpdump is installed when creating the container image.
Ran locally SimpleNetworkRecipe. Works fine.
@Axonis @Kuba314 @olichtne @enhaut
> Update containers fedora release

- lnst/Recipes/ENRT/GeneveLwtTunnelRecipe.py
- lnst/Recipes/ENRT/GeneveOvsTunnelRecipe.py
- lnst/Recipes/ENRT/GeneveTunnelRecipe.py
- lnst/Recipes/ENRT/GreLwtTunnelRecipe.py
- lnst/Recipes/ENRT/GreOvsTunnelRecipe.py
- lnst/Recipes/ENRT/GreTunnelOverBondRecipe.py
- lnst/Recipes/ENRT/GreTunnelOverMacvlanRecipe.py
- lnst/Recipes/ENRT/GreTunnelOverVlanRecipe.py
- lnst/Recipes/ENRT/GreTunnelRecipe.py
- lnst/Recipes/ENRT/Ip6GreNetnsTunnelRecipe.py
- lnst/Recipes/ENRT/Ip6GreTunnelRecipe.py
- lnst/Recipes/ENRT/Ip6TnlTunnelRecipe.py
- lnst/Recipes/ENRT/IpIpTunnelRecipe.py
- lnst/Recipes/ENRT/L2TPTunnelRecipe.py
- lnst/Recipes/ENRT/SitTunnelRecipe.py
- lnst/Recipes/ENRT/VxlanGpeTunnelRecipe.py
- lnst/Recipes/ENRT/VxlanLwtTunnelRecipe.py
- lnst/Recipes/ENRT/VxlanNetnsTunnelRecipe.py
- lnst/Recipes/ENRT/VxlanOvsTunnelRecipe.py
This updates all ENRT recipes that inherit from BaseTunnelRecipe so that underlying network IP/IP6 address is parametrized, either `net_ipv4` or `net_ipv6` or both.
The MR is based on https://github.com/LNST-project/lnst/pull/265 and must be merged onlywhen that MR is merged.
Tested locally and in RedHat labs.
> Add ip adress param to tunnel recipes

- pyproject.toml
With update of pyroute2 to 0.7.4 we hit a bug described in
https://github.com/svinota/pyroute2/issues/1068
The bug is triggered from Agent's InterfaceManager code when calling
IPRSocket.put().
This bug breaks github CI for lnst and esentially any run of LNST recipe,
so this is a temporary fix to use pyroute2 0.7.3 until the issue is resolved.
CI is sufficient
@olichtne
> pyproject.toml: enforce pyroute2 0.7.3

- docs/source/linux_bridge_recipe.rst
- docs/source/specific_scenarios.rst
- lnst/Recipes/ENRT/LinuxBridgeRecipe.py
- lnst/Recipes/ENRT/__init__.py
This adds new recipe into ENRT recipe set. The network configuration is:
* a linux bridge device configured on top of bare NIC
* ipv4 and ipv6 address is configured on the bridge
* the test does not have any performance tweaks compared to e.g. SimpleNetworkRecipe
Ran tests internally.
@olichtne
> Add linux bridge recipe

- docs/source/linux_bridge_over_bond_recipe.rst
- docs/source/specific_scenarios.rst
- lnst/Recipes/ENRT/LinuxBridgeOverBondRecipe.py
- lnst/Recipes/ENRT/__init__.py
This adds new recipe into ENRT recipe set. The network configuration is:
* a bond device is created over two NICs
* a linux bridge device is created and bond device is added to the bridge
* ipv4 and ipv6 address is configured on the bridge
* the test does not have any performance tweaks compared to e.g. SimpleNetworkRecipe
Tested with containers locally (removed one DeviceReq form the code as containers do not support that).
Redhat lab job id 7503695
@all
> Add linux bridge over bond recipe

- lnst/Recipes/ENRT/BaseTunnelRecipe.py
This enables all recipes derived from BaseTunnelRecipe to run performance tests.
Test run of GreTunnelRecipe in RH labs, job id 7512901.
> Recipes/BaseTunnelRecipe: add generate_perf_endpoints()

- pyproject.toml
This reverts commit 4e9ea1f0a20b3d3213e5f272fdac22e70b0c7a94.
The pyroute2 issues has been fixed, https://github.com/svinota/pyroute2/issues/1068#issuecomment-1407366608
github CI covers this.
@olichtne
> Revert "pyproject.toml: enforce pyroute2 0.7.3"

- lnst/Recipes/ENRT/GreLwtTunnelRecipe.py
- lnst/Recipes/ENRT/VxlanGpeTunnelRecipe.py
These tests assign IP addresses not directly on the tunnel interfaces but on a loopback interface. So, the BaseTunnelRecipe.generate_perf_endpoints needs to be overridden to use loopback's IP addresses for the performance test.
Before the fix, running the tests would crash with:
```
Traceback (most recent call last):
File "/mnt/tests/data.lnst.anl.lab.eng.bos.redhat.com/data-server-content/gitlab-tasks/beaker-lnst-tasks/master.tar.gz/lnst/test-runner/./do-my-test", line 34, in main
ctl.run(recipe)
File "/root/virtualenvs/rhextensions-lnst-Xo1BSm3a-py3.9/lib/python3.9/site-packages/lnst/Controller/Controller.py", line 172, in run
recipe.test()
File "/root/rhextensions-lnst/lnst/RHExtensions/RHRecipeMixin.py", line 79, in test
super(RHRecipeMixin, self).test()
File …
```
> Recipes/ENRT/{Gre,VxlanGpe}TunnelRecipe.py: override generate_perf_endpoints()

- lnst/Recipes/ENRT/VxlanRemoteRecipe.py
This allows the recipe to configure offloads.
Beaker job id 7531270
> Recipes/ENRT/VxlanRemoteRecipe: extend with OffloadSubConfigMixin

- lnst/Recipes/ENRT/ConfigMixins/OffloadSubConfigMixin.py
Even if empty offload list is used for a recipe using the mixin the `_check_test_offload_conflicts` is called. This raises an exception because it attempts to access non existing attribute of the config object.
Fixes #287
Internal RH lab Beaker job id 7543578. The job covers VxlanRemoteRecipe with both default empty offload_combinations and one offload combination.
* default 
```
'offload_combinations': (),
...
Sub configuration description:
NIC offload configuration skipped
...
Flow(
type=udp_stream,
generator=Host(machine_id=host1), 
generator_bind=192.168.100.1,
generator_nic=VxlanDevice(machine=host1, id=vxlan0, name=t_vxlan0, ifindex=10),
receiver=Host(machine_id=host2), 
receiver_bind=192.168.100.2,
receiver_nic=VxlanDevice(machine=host2, id=vxlan0, name=t_vxlan0, ifindex=10), …
```
> ENRT.OffloadSubConfigMixin: fix empty offloads use case

- lnst/Agent/Agent.py
- lnst/Recipes/ENRT/SimpleMacsecRecipe.py
* setting initial state of used devices to down -
* Sometimes may happen, that used interfaces are not in down state which may leads to nondeterministic behaviour of recipes that relies on initial state of device. Setting used device to down state as part of pre-test configuration sets same initial state of devices across the recipes.
* Removed setting devices down from MACsec recipes, which was just 
workaround
Scheduled 1 test for each recipe class we have with my changes `J:7541084` and without my changes `J:7541167` to check whether my changes breaks (changes) indexing or not (should not).
> Setting initial state of used devices to down

- lnst/RecipeCommon/Perf/Measurements/LinuxPerfMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/Results/LinuxPerfMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/__init__.py
Previously, the `_jobs` list was initialized only once, leading to jobs
from multiple iterations being appended. This led to errors when zipping
with current configurations and killing the jobs.
Moving the `_jobs` variable to the constructor fixes this issue.
`J:7588038` - ~~have to confirm it's fixed once the job finishes.~~
@enhaut @olichtne 
Closes: #290
> Linuxperf fix

- lnst/RecipeCommon/Perf/Evaluators/BaselineTcRunAverageEvaluator.py
- lnst/RecipeCommon/Perf/Evaluators/MaxTimeTakenEvaluator.py
- lnst/RecipeCommon/Perf/Measurements/Results/AggregatedTcRunMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/TcRunMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/TcRunMeasurement.py
Previously we where evaluating `time_taken`. This changes it to evaluate `rules/sec`
> Using rules/sec for TrafficControlRecipe results

- lnst/RecipeCommon/Perf/Measurements/Results/AggregatedTcRunMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/TcRunMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/TcRunMeasurement.py
- lnst/Tests/TrafficControl.py
Changing to perf paralell result. mostly complete. commiting for test and review purposes. 
Also use asyncio.subprocess to run multiple tc instances client side. 
For reference here is a sample of the `tc` process start timestamps: 
```
data:
instance_results:
item 0:
...
start_timestamp: 1681069428.9487906
...
item 1:
...
start_timestamp: 1681069428.9511075
... 
item 2:
...
start_timestamp: 1681069428.9530337
...
item 3:
...
start_timestamp: 1681069428.9548721
...
```
> Use PerfParalellResult and `asyncio.subprocess` for TrafficControl results

- lnst/Recipes/ENRT/ConfigMixins/OffloadSubConfigMixin.py
Resolves #300
Since kernel 5.10 GRO is enabled for UDP:
https://developers.redhat.com/articles/2021/11/05/improve-udp-performance-rhel-85#benchmarking_gro
Tested with following test configuration:
```
recipe = SimpleNetworkRecipe(                                                   
ping_count=1,                                                               
perf_duration=5,                                                            
perf_iterations=1,                                                          
perf_parallel_processes=1,                                                  
perf_tests=['udp_stream'],                                                  
ip_versions=['ipv4'],                                                       
perf_msg_sizes=[16384], …
```
> Recipes/OffloadSubConfigMixin.py: remove gro offload config check

- lnst/Recipes/ENRT/SRIOVNetnsTcRecipe.py
Using devlink to switch card back to legacy mode
wasn't working due to device being busy
Tc qdisc was causing the command to hang up and fail
Fixes:
```
[root@server ~]# devlink dev eswitch set pci/0000:81:00.0 mode legacy
Error: mlx5_core: Can't change mode, E-Switch is busy.
kernel answers: Device or resource busy
```
Manual run:
```
[root@server ~]# tc qdisc del dev p5p1 ingress
[root@server ~]# devlink dev eswitch set pci/0000:81:00.0 mode legacy
```
> Recipes.ENRT.SRIOVNetnsTcRecipe: delete qdisc

- lnst/Common/Utils.py
- lnst/Devices/Device.py
These methods will call up/down on a interface and wait for it to be in the desired state or raise an exception.
Tested locally by running `.github/runner.py` and replacing `.up()` with `.up_and_wait(timeout=5)`.
@LNST-project/lnst-developers 
Closes: #305
> Device: Add {up,down}_and_wait methods

- lnst/Recipes/ENRT/ConfigMixins/MultiCoalescingHWConfigMixin.py
- lnst/Recipes/ENRT/ConfigMixins/PerfReversibleFlowMixin.py
- lnst/Recipes/ENRT/IpsecEspAeadRecipe.py
- lnst/Recipes/ENRT/IpsecEspAhCompRecipe.py
- lnst/Recipes/ENRT/OvSDPDKBondRecipe.py
- lnst/Recipes/ENRT/OvS_DPDK_PvP.py
- lnst/Recipes/ENRT/VhostNetPvPRecipe.py
- lnst/Tests/Iperf.py
PR https://github.com/LNST-project/lnst/pull/306 changed how cpupin parameter is used. I forgot to update other recipes that use the PerfFlow directly. This PR fixes that.
J:8023660, no coverage for perf_reverse as we have no tests in the database.
@olichtne
> Recipes/ENRT: fix recipes after cpupin split

- lnst/Devices/BondDevice.py
- lnst/Recipes/ENRT/BaseLACPRecipe.py
- lnst/Recipes/ENRT/ConfigMixins/BaseRESTConfigMixin.py
- lnst/Recipes/ENRT/DellLACPRecipe.py
- lnst/Recipes/ENRT/__init__.py
- pyproject.toml
* Since LACP requires breaking switch configuration, it needs to be configured dynamically. Following classes does the job:
* `DellLACPRecipe` support of dell's REST API [documentation here](https://www.dell.com/support/manuals/en-us/smartfabric-os10-emp-partner/smartfabric-os-user-guide-10-5-4/lacp-individual-port-feature-interactions?guid=guid-03d5c911-7eeb-406f-842a-c133e710b405&lang=en-us)
* `BaseLACPRecipe` the base class that is missing switch-specific configuration (e.g. `DellLACPRecipe`)
* `BaseRESTConfigMixin` REST API abstraction
* fixed setting xmit hash policy
* Support of spreading multiple flows to multiple IPs
```
ssl_verify=False
api_url='https://example.com'
perf_spread_parallel_over_ips=True
rest_user='xxxx'
rest_password='xxxx' …
```
> LACP support

- lnst/RecipeCommon/Perf/Measurements/LinuxPerfMeasurement.py
- lnst/Recipes/ENRT/BaremetalEnrtRecipe.py
- lnst/Recipes/ENRT/MeasurementGenerators/LinuxPerfMeasurementGenerator.py
- lnst/Recipes/ENRT/SimpleNetworkTunableRecipe.py
The SimpleNetworkTunableRecipe uses different cpupin parameters and therefore cannot use the LinuxPerfMeasurementGenerator in its current form.
This patch enhances the LinuxPerfMeasurement so that perf tool can profile different sets of cpus on recipe hosts.
Tested locally, for the recipes inheriting from BaremetalEnrtRecipe the change is transparent. Tested also the SimpleNetworkTunableRecipe.
Scheduled tests in Beaker: J:8062080 J:8062081
Closes: #315
> Fix linuxperf measurement for SimpleNetworkTunableRecipe

- lnst/RecipeCommon/Perf/Measurements/BaseCPUMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/BaseFlowMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/Results/BaseMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/CPUMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/FlowMeasurementResults.py
Previously the descriptions were generated directly or almost directly as part of the Measurement classmethod "report_results" which also creates a RecipeResult object that is added to the current RecipeRun instance.
This meant that it wasn't possible to do custom descriptions or custom result objects without calling this "report_results" method which would also create the recipe result object.
This refactors the code a bit so that the MeasurementResult description is generated directly by the MeasurementResult object and the "report_results" method simply calls this when needed.
Unfortunatelly this means that the format for the CPUMeasurementResults has to change a bit as these are not grouped by "host" anymore and each individual result will contain the host id.
CI tests should be ok …
> RecipeCommon.Perf.MeasurementResults: refactor result description generation

- lnst/RecipeCommon/Perf/Measurements/TcRunMeasurement.py
- lnst/Recipes/ENRT/TrafficControlRecipe.py
- lnst/Tests/TrafficControl.py
Previously, the `TrafficControlRecipe` didn't use `StatCPUMeasurement` and didn't allow users to pin CPUs. This now works even with a CPU pinning policy (similar to perf pinning).
J:8172306
@jtluka @olichtne
> Add CPU pinning to TrafficControlRecipe

- container_files/Dockerfile
- lnst/Common/Parameters.py
- lnst/RecipeCommon/Perf/Measurements/BaseFlowMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/RDMABandwidthMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/Results/AggregatedRDMABandwidthMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/BaseMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/RDMABandwidthMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/__init__.py
- lnst/RecipeCommon/Perf/Measurements/__init__.py
- lnst/Recipes/ENRT/BaseEnrtRecipe.py
- lnst/Recipes/ENRT/MeasurementGenerators/BaseFlowMeasurementGenerator.py
- lnst/Recipes/ENRT/SimpleNetworkRecipe.py
- lnst/Recipes/ENRT/SoftwareRDMARecipe.py
- lnst/Recipes/ENRT/__init__.py
- lnst/Tests/RDMABandwidth.py
- lnst/Tests/__init__.py
Adds RDMA (Remote Direct Memory Access) testing using [linux-rdma/perftest](https://github.com/linux-rdma/perftest)'s program `ib_send_bw`. In order for this measurement to work, we have to have an RDMA-capable pair of devices on two hosts. These are currently setup in software using `rdma link add`. There's also an option for hardware RDMA, which requires RDMA-capable NICs. Software RDMA can run on any NIC supporting Ethernet.
Currently, there are two software methods that enable RDMA - `rxe` (Soft-RoCE (Software RDMA over Converged Ethernet)) and `siw` (Software iWARP). One of these has to be selected in the recipe parameters.
J:8103516
> Add RDMA bandwidth testing capability

- docs/source/conf.py
This seems to have changed on the readthedocs side and is now I think required to be set.
(Please provide a list of tests that prove that the pull
request doesn't break the stable state of the master branch. This should
include test runs with valid results for all of critical workflows.)
(Please add a list of reviewers that should check the validity and sanity of
this merge request before it's accepted. Use the `@username` syntax. If you
don't know who to mention just link `@all`.)
Closes: #
> docs/source/conf.py: fix html_theme setting

- lnst/Common/Utils.py
- lnst/RecipeCommon/Perf/Measurements/Results/AggregatedXDPBenchMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/XDPBenchMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/__init__.py
- lnst/RecipeCommon/Perf/Measurements/XDPBenchMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/__init__.py
- lnst/Recipes/ENRT/MeasurementGenerators/XDPFlowMeasurementGenerator.py
- lnst/Recipes/ENRT/XDPDropRecipe.py
- lnst/Tests/PktGen.py
- lnst/Tests/XDPBench.py
- lnst/Tests/__init__.py
* added `Utils.kmod_loaded` function that checks whether module is loaded or not 
* PktGen test module implementation
* PktGen is connection-less packet generator that simply "injects" packets to NIC's TX buffer. Because of that it requires `pktgen` kernel module if kernel wasn't compiled with `CONFIG_NET_PKTGEN` flag.
* Outputs of devices are at the end parsed to `PktGen._res_data` attr in following format: `{[OUTPUT_DEV]: {"params": {DEVICE_CONFIGURATION}, "current": {CURRENT_STATS}, "state": "[ACTUAL_STATE]"}}`
* `XDPBench` test module that utilizes [xdp-bench](https://github.com/xdp-project/xdp-tools/tree/master/xdp-bench)
* see problem with output reading https://github.com/xdp-project/xdp-tools/issues/344
* `XDPDropRecipe` is basically just `SimpleNetworkRecipe` that uses …
> Added XDP testing capability

- lnst/Recipes/ENRT/BaseEnrtRecipe.py
- lnst/Recipes/ENRT/PingFloodRecipe.py
This allows us to leave out the driver and make mapper match NICs with any driver param.
Keeping driver default in `TrafficControlRecipe` makes sense, because not every NIC supports steering.
Not tested.
> Remove driver param defaults

- lnst/Controller/RunSummaryFormatters/JsonRunSummaryFormatter.py
We want to know from the json-formatted run results to know that an exception happened during a recipe run. One way would be to change the format of the output to something like `{"exception_happened": false, "results": [...]}`. Another option is to format the exception as its own custom result with a type `"exception"`.
I don't feel strongly about the decision I made, I think semantically they are equivallent, but this one doesn't unnecessarily indent all the other results. On top of that, why can't an exception be a result? It's not a thing that's somehow related to the whole run. It's just the reason-result that terminated it.
Tested locally as part of an effort to use json results instead of lrcs. I however did not test this on a run with an actual exception I don't think. …
> Format run exception as its own result

- lnst/Controller/RunSummaryFormatters/JsonRunSummaryFormatter.py
- lnst/RecipeCommon/Perf/Evaluators/BaselineEvaluator.py
We can format all results, because all have a failure value and description that's json serializable. The data just isn't known if the result type is not known so it can't be formatted.
> JsonRunSummaryFormatter: format all results

- lnst/External/TRex/TRexLib.py
- lnst/Recipes/ENRT/BasePvPRecipe.py
- lnst/Recipes/ENRT/OvS_DPDK_PvP.py
Current implementation of Ovs_DPDK_PvP recipe works only for ixgbe/intel nics. Using the same setup with Mellanox cards requires sligh adjustments that include:
* no `driverctl set-override`
* use `--no-ofed-check` for TRex, the ofed utils are not required for this
Tested on i40e and mlx5_core NICs.
> ovs dpdk fixes for mellanox

- lnst/RecipeCommon/Perf/Measurements/Results/XDPBenchMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/XDPBenchMeasurement.py
All other `MeasurementResults.describe()` methods returns already formatted string, so our internal tooling expects string not the list of strings, and therefore it crashes when treating list as a string.
Before: `J:8418399`  
After: `J:8433522`
@olichtne @jtluka
> XDPMeasurementResults: fixed describe method return value type

- lnst/Controller/RunSummaryFormatters/JsonRunSummaryFormatter.py
Sometimes non-formattable values (such as `Device` objects) are set.
This wasn't caught earlier, because I wasn't testing with recipes which would actually set device attributes to other devices.
Not much, but should work.
@olichtne
> JsonRunSummaryFormatter: Wrap attr_set values in repr

- lnst/Recipes/ENRT/BaseLACPRecipe.py
BaseLACPRecipe reimplements same behaviour as DoubleBondRecipe but adds multiple IPs. Because direct parent also implements bond device setup we need to bypass direct parent's `test_wide_conf()` method to prevent LNST crashing on calling bond device setup twice.
Excluding changes: `J:8469701`  
Including changes: `J:8470332`
> BaseLACPRecipe.test_wide_conf(): call grand parent's test_wide_conf() method

- lnst/Recipes/ENRT/SRIOVNetnsTcRecipe.py
Dumping rules makes it easier to analyze whether the offload is actually used for tc.
J:8480924
@olichtne @Axonis
> Recipes/SRIOVNetnsTcRecipe.py: dump tc rules after performance test

- lnst/Controller/RunSummaryFormatters/JsonRunSummaryFormatter.py
- lnst/RecipeCommon/Perf/Measurements/RDMABandwidthMeasurement.py
Report rdma bandwidth data in a measurement result along its description. Also include rdma-bandwidth measurement formatting in JsonRunSummaryFormatter.
Ran locally, produced rdma-bandwidth measurement result with actual data.
> Fix RDMA measurement data reporting

- lnst/Recipes/ENRT/BaseSRIOVNetnsTcRecipe.py
- lnst/Recipes/ENRT/SRIOVNetnsGeneveTcRecipe.py
- lnst/Recipes/ENRT/SRIOVNetnsTcRecipe.py
- lnst/Recipes/ENRT/SRIOVNetnsVxlanTcRecipe.py
- lnst/Recipes/ENRT/__init__.py
This pull request adds new tests SRIOVNetns[Vxlan|Geneve]TcRecipe. To avoid code duplication I moved most of the functionality to
a new base class BaseSRIOVNetnsTcRecipe and updated the existing SRIOVNetnsTcRecipe to use the base class.
The new base class provides two common methods that the derived class overrides:
* `add_tc_filter_rules()` (must be defined by every derived class)
* `add_network_layers()` (optional, to define additional network stacks, for example tunnels between VFs)
~~J:8496033~~
~~J:8496862 (with geneve)~~
J:8508546
@Axonis @olichtne
> Add vxlan hw tc offload

- lnst/Devices/Device.py
Recently the formatting of the ethtool output changed, where the values are now aligned and may contain multiple spaces.
Fixes following exception when rx-usecs setting is restored:
```
2023-11-20 07:21:21       (localhost)        -    INFO: Result: PASS, What: Setting Device attribute host1.eth0.coalescing_rx_usecs = None, previous value = None
2023-11-20 07:21:21           (host1)        -   ERROR: Command "ethtool -C ens7f0np0 rx-usecs None" execution failed (exited with 1)
2023-11-20 07:21:21       (localhost)        -   ERROR: Recipe execution terminated by unexpected exception
LNST Controller crashed with an exception:
Traceback (most recent call last):
File "/mnt/tests/prod.ci-vm.lnst.hosted.psi.rdu2.redhat.com/data-server-content/gitlab-tasks/beaker-lnst-tasks/master.tar.gz/lnst/te …
```
> Devices/Device.py: update the regex for ethtool coalesce settings

- container_files/Dockerfile
- lnst/Agent/Agent.py
- lnst/Agent/Job.py
- lnst/Recipes/ExampleRecipe.py
Job timeouts should be reported as failures.
`J:8577504`
@jtluka 
Closes: #233
> Report job timeouts as FAIL

- lnst/Devices/Device.py
In some cases a query of switchdev info on a device could return an empty string. When this happens the code expects either legacy or switchdev mode in the output, otherwise a DeviceError is raised.
The DeviceError causes termination of the machine's device cleanup process and some devices may be left without deconfiguration.
Since this case should not be considered as a critical issue a DeviceFeatureNotSupported is raised instead that is accepted during the deconfiguration.
(Please provide an overall description of what your Merge request is trying to
do.)
(Please provide a list of tests that prove that the pull
request doesn't break the stable state of the master branch. This should
include test runs with valid results for all of critical workflows.)
(Please add a list of reviewers that …
> HOTFIX Devices/Device.py: report unsupported feature for switchdev corner case

- lnst/Recipes/ENRT/GeneveTunnelRecipe.py
- lnst/Recipes/ENRT/GreTunnelRecipe.py
- lnst/Recipes/ENRT/LinuxBridgeOverBondRecipe.py
- lnst/Recipes/ENRT/LinuxBridgeRecipe.py
To tune recipes for stable performance measurements they need to be extended with config mixins, in particular DevInterruptHWConfigMixin. 
* J:8753017 without tuning
* J:8753015 with tuning dev_intr_cpu=[0]
@olichtne
> Recipes/ENRT: extend some recipes with config mixins

- lnst/Agent/Agent.py
- lnst/Agent/Job.py
See commit message bodies for more info.
Normal SimpleNetworkRecipe execution passes, interrupting with ^C during iperf test also finishes well and doesn't crash agents. Not sure if this is enough testing though...
Closes: #354
> Fix job cleanup on agents

- lnst/Recipes/ENRT/MPTCPRecipe.py
- lnst/Recipes/ENRT/MeasurementGenerators/BaseFlowMeasurementGenerator.py
This PR makes our MPTCP recipe actually test 2 flows. It also makes perf flows not bind on client ports, because currently there's a kernel bug which keeps ports open even after they're closed.
Tested manually, 2 subflows now work.
@olichtne @jtluka
> Fix MPTCP recipe

- lnst/Agent/Job.py
- lnst/Tests/Iperf.py
Improve iperf reporting and reorganize the code a bit.
`J:8583736` - second recipeset contains debug logs.
@jtluka 
Closes: #201
> Reorganize Iperf error reporting

- lnst/Tests/XDPBench.py
Just for the sake of completeness we should be able to see xdp-bench command that is being executed as it calls Popen and currently isn't logged.
None required, simple change
Closes: #
> Tests.XDPBench: add logging of xdp-bench cmd

- lnst/RecipeCommon/Perf/Measurements/BaseFlowMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/BaseMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/IperfFlowMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/NeperFlowMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/RDMABandwidthMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/TRexFlowMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/TcRunMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/XDPBenchMeasurement.py
- lnst/RecipeCommon/Perf/Recipe.py
- lnst/Recipes/ENRT/BaseEnrtRecipe.py
- lnst/Recipes/ENRT/OvS_DPDK_PvP.py
- lnst/Recipes/ENRT/TrafficControlRecipe.py
The "bottom" measurements - meaning the most core measurement in a list of measurements that we may run can now be "simulated".
This means that instead of actually running the measurement tools/commands we instead run the following command:
echo simulated start
And instead of returning real measurement results we return the same structure of data with a single 0 value perf interval.
Combining this we can now run all of our ENRT recipes in a "simulation" that preserves the number of commands per test recipe run and should return results compatible with all of our tooling with just the basic 0 value.
The cpu measurement simulation does actually call the real measurement, this is because this isn't a "bottom/core" measurement and is instead designed to always wrap some other measurement.
I …
> PerfMeasurements: add ability to simulate measurements

- lnst/Devices/Device.py
If no tc utility is present on the agent system, exec_cmd() raises an exception. If uncaught, the previous address flush request will also not complete. The address remaining in place will cause an EEXIST error upon next test run, requiring manual intervention to resolve the situation.
Fixes: 49e523d5aef46 ("Slave: Add basic support for tc.")
> Devices/Device.py: Fix for broken cleanup() with missing tc tool

- lnst/Common/ExecCmd.py
- lnst/RecipeCommon/FirewallControl.py
- lnst/Recipes/ENRT/ConfigMixins/FirewallMixin.py
The set of classes contained in this module enable users to push
firewall rulesets onto the hosts used for test runs.
There are five flavors to choose from for the actual firewall
implementation, with descriptive names:
* NftablesMixin
* IptablesMixin
* Ip6tablesMixin
* EbtablesMixin
* ArptablesMixin
To use the provided functionality, inherit one of them and either
provide a dictionary of "host: ruleset" entries in a property
'firewall_rulesets' or overwrite the 'firewall_rulesets_generator()'
method with a generator yielding as many dictionaries a desired for
performing a test run with. The latter provides a simple means of
testing with gradually increasing or extending rulesets.
In order to perform post-processing on rulesets after a test run,
override the 'firewall_rulesets' setter …
> Recipes/ENRT/ConfigMixins: Add FirewallMixin.py

- lnst/Agent/InterfaceManager.py
- lnst/Controller/Machine.py
Resolves an issue when moving a veth device to a namespace. The device will
have _nl_link_update populated with data from generic Device creation (device
appears in the namespace). This data may cause issues for certain device
operations like setting the link up.
To avoid this, clearing the _nl_link_update while remapping the device
solves the issue.
Fixes #367
Tested with the reproducer from the issue both in container setup and normal setup.
I scheduled test run in RH labs that include a single run of each recipe type, beaker job id J:9261245
@olichtne
> Fix veth device move

- lnst/Tests/Ping.py
Sometimes it's useful to have ping stdout available to analyze the connectivity issues.
Tested in RH Beaker lab J:9341216
@olichtne
> Tests/Ping: log stdout

- lnst/Recipes/ENRT/ConfigMixins/BaseRESTConfigMixin.py
For various reasons, it may happen that a remote resource is unreachable/doesn't respond with an expected response. Therefore, retry mechanism for API calls tries to send request `tries` times with `1sec` sleep in between.
* Beaker job `J:9529957`
* manual tests of retries by changing `/etc/hosts` file to simulate resource is unreachable
> BaseRESTConfigMixin: retrying of API call

- lnst/Common/BaseModule.py
- lnst/Common/IpAddress.py
- lnst/Common/conditions/WaitForConditionModule.py
- lnst/Common/conditions/WaitForEstablishedConnections.py
- lnst/Controller/Job.py
- lnst/Controller/Namespace.py
- lnst/Devices/Device.py
- lnst/Recipes/ENRT/CTFulltableInsertionRateRecipe.py
- lnst/Recipes/ENRT/CTInsertionRateNftablesRecipe.py
- lnst/Recipes/ENRT/ConfigMixins/FirewallMixin.py
- lnst/Recipes/ENRT/ConfigMixins/LongLivedConnectionsMixin.py
- lnst/Recipes/ENRT/ConfigMixins/NftablesConntrackMixin.py
- lnst/Recipes/ENRT/MeasurementGenerators/BaseFlowMeasurementGenerator.py
- lnst/Recipes/ENRT/__init__.py
- lnst/Tests/BaseTestModule.py
- lnst/Tests/LongLivedConnections.py
- lnst/Tests/__init__.py
* added `WaitForConditionModule` which implements waiting for condition on _remote_ agent
* FirewallMixin: fixed pickling for dynamic derived classes
* added conntrack insertion rate recipe
* added conntrack full table insertion rate recipe
Waiting for condition module and firewall mixin changes are used in conntrack recipes, so test run of both conntrack insertion rate and ct full table insertion rate recipes is sufficient to test all the changes from this mr.
`J:9753788`
Closes https://github.com/LNST-project/lnst/issues/372
> Conntrack: insertion rate recipe, full table insertion rate recipe

- .github/runner.py
- lnst/Controller/ContainerPoolManager.py
With podman5+ the CNI network backend support is removed, with netavark being the default network plugin.
This adds support for netavark network backend and changes the ContainerPoolManager to use it as default.
The CNI backend support is kept and user can force LNST to use it by `ContainerPoolManager(network_plugin='cni')`.
Tested on Fedora40 with podman-5.2.2-1.fc40.x86_64
@olichtne @enhaut
> ContainerPoolManager: add netavark support

- lnst/Tests/PktGen.py
Current implementation of PktGen module incorrectly uses `{src,dst}6_{min,max}` attributes to configure pktgen. However, it should be just `{src,dst}6` for IPv6, see pktgen commands reference e.g. https://wiki.linuxfoundation.org/networking/pktgen.
* IPv4 xdp tests - `J:9962254`, `J:9971061`
* IPv6 xdp tests - `J:9962320`, `J:9967242`
> PktGen: fixed IPv6 src,dst addrs attributes

- lnst/RecipeCommon/Perf/Measurements/IperfFlowMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/NeperFlowMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/Results/FlowMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/NeperFlowMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/TRexFlowMeasurement.py
This should fix the issues we regularly see with lnst crashing with exception when iperf failed to establish a connection. The source of the issue is that the created perf result data structure was slightly different.
While testing this I also found issues with the warmup/warmdown timestamp calculation because the zero created zero iperf measurements don't have a duration long enough to include a warmup/warmdown... this however shouldn't crash the trimming and should instead return another zero measurement.
(Please provide a list of tests that prove that the pull
request doesn't break the stable state of the master branch. This should
include test runs with valid results for all of critical workflows.)
@jtluka @enhaut @Axonis 
Closes: #
> Fix iperf no connection and PerfResult warmup timestamp calculation

- docs/source/bonding_mixin.rst
- docs/source/config_mixin_classes/use_vfs_mixin.rst
- docs/source/config_mixins.rst
- docs/source/specific_scenarios.rst
- lnst/Devices/Device.py
- lnst/Recipes/ENRT/BondRecipe.py
- lnst/Recipes/ENRT/BondingMixin.py
- lnst/Recipes/ENRT/DoubleBondRecipe.py
- lnst/Recipes/ENRT/UseVfsMixin.py
- lnst/Recipes/ENRT/VlansOverBondRecipe.py
This replaces original messed up PR https://github.com/LNST-project/lnst/pull/379
This adds vf_trust parameter to UseVfsMixin. The Device class is extended with vf_trust() method.
Tests
This also updates BondRecipe, VlansOverBondRecipe and DoubleBondRecipe with fail_over_mac. To avoid code duplication I refactored these classes to us new BondingMixin class that adds the common bonding recipe parameters and provides a method to create the bonding devices.
J:10034309
Reviews
@olichtne
> UseVfsMixin: add vf_trust parameter

- lnst/RecipeCommon/Perf/Measurements/XDPBenchMeasurement.py
- lnst/Recipes/ENRT/MeasurementGenerators/XDPFlowMeasurementGenerator.py
- lnst/Recipes/ENRT/XDPTxRecipe.py
- lnst/Recipes/ENRT/__init__.py
- lnst/Tests/XDPBench.py
* exported parameters of `XDPBench` test tool to measurement
* added XDP tx test
The test measures how fast the CPU can read an incoming packet, swap MACs and send it back using the same NIC. It's basically hairpinning
Functional test ox xdp drop + xdp tx recipes in `J:10038813`
> Added XDP tx recipe

- lnst/RecipeCommon/Perf/Measurements/BaseCPUMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/BaseFlowMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/IperfFlowMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/LinuxPerfMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/NeperFlowMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/RDMABandwidthMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/Results/AggregatedCPUMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/AggregatedFlowMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/AggregatedLinuxPerfMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/AggregatedRDMABandwidthMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/AggregatedTcRunMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/AggregatedXDPBenchMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/BaseMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/CPUMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/FlowMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/LinuxPerfMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/RDMABandwidthMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/StatCPUMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/TcRunMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/Results/XDPBenchMeasurementResults.py
- lnst/RecipeCommon/Perf/Measurements/StatCPUMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/TRexFlowMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/TcRunMeasurement.py
- lnst/RecipeCommon/Perf/Measurements/XDPBenchMeasurement.py
This is necessary to detect situation when something went wrong with the measurement and we should disqualify the measurement results from being fully trustworthy, e.g. for setting baselines.
Needs to be tested for all types of measurements, ideally with failures in the measurement process to see the changed results.
@Axonis @enhaut @jtluka 
Closes: #
> Fail measurements if any of the jobs returned issues

- pyproject.toml
After poetry-core update the default of the includes changed so that they're only in the sdist by default and this breaks our lnst installation as the schema file is used during runtime.
(Please provide a list of tests that prove that the pull
request doesn't break the stable state of the master branch. This should
include test runs with valid results for all of critical workflows.)
(Please add a list of reviewers that should check the validity and sanity of
this merge request before it's accepted. Use the `@username` syntax. If you
don't know who to mention just link `@all`.)
Closes: #
> pyproject.toml: add includes into wheel

- pyproject.toml
Starting from version 0.9.1 pyroute2 will use asyncio-based core, and even if the project continues to provide the synchronous API, there might be some incompatible things.
So until we prepare and discuss a PR to align the code with the current pyroute2 master branch, restrict the version to avoid occasional failures when pyroute2 0.9.1 will be released.
This PR only fixes the current state, no additional functionality is added.
@jtluka 
@olichtne
> pyproject.toml: add pyroute2 version constraint

- lnst/RecipeCommon/Perf/Measurements/XDPBenchMeasurement.py
XDP's test modules might raise an exception when running on agent
machine. Currently these are not propagated to conroller, so it treats
incomplete/wrong results as a valid ones and so, controller crashes
on weird issues because of that.
- no crash test (just to be sure everything works as expected) `J:10515937`
- crash test (to test added code) `J:10515938`
> Better XDP error handling

- lnst/RecipeCommon/Perf/Measurements/LinuxPerfMeasurement.py
- lnst/Recipes/ENRT/MeasurementGenerators/LinuxPerfMeasurementGenerator.py
- lnst/Recipes/ENRT/VirtualEnrtRecipe.py
- lnst/Tests/LinuxPerf.py
This enables LinuxPerfMeasurement in virtual recipes.
This also fix an issue when perf archive fails - it is a potential issue noticed in RHEL9.6, however unsuccesful archiving currently results in exception. Missing archived data still can be installed through appropriate debuginfo rpm.
J:10794035
@olichtne
> Virt linuxperf

- docs/source/installation.rst
Without this the ping command runs forever meaning that it will timeout and be killed from the machine.run command.
This can be confusing for new users.
ci is enough
> docs/installation: add -c10 to ping command

- lnst/RecipeCommon/Ping/Recipe.py
- lnst/Recipes/ENRT/BaseEnrtRecipe.py
Negative ping test with count=100 and interval 0.2 can take significantly more that the default timeout of 60 seconds that leads to termination of the ping test and reporting exception.
The patch set fixes this by calculating estimation based on the count and interval parameter. For positive test, the estimate is `(count*interval + 10)` seconds, for negative `(2*count)` seconds.
Tested in  beaker job 11332804 
@olichtne
> RecipeCommon/Ping/Recipe.py: estimate the ping duration based on interval and count

- lnst/Recipes/ENRT/ConfigMixins/DevNfcRxFlowHashConfigMixin.py
If we're requesting any of the "non-symmetric" hash options we should disable symmetric hashing, otherwise the configuration is considered invalid and may error out.
This is based on an internal discussion investigating a potential regression, it turns out that when symmetric hashing is enabled configuring the `rx-flow-hash` option to use only one of src or dst fields is invalid and not supported.
This is explained in: https://elixir.bootlin.com/linux/v6.16-rc4/source/net/ethtool/ioctl.c#L1021
tested via internal beaker job: `J:11347282`
@jtluka 
Closes: #
> DevNfcRxFlowHashConfigMixin: disable symmetric hashing

- lnst/Common/ExecCmd.py
- lnst/Common/Parameters.py
- lnst/Devices/Device.py
Some commands are expected to fail especially with virtual NICs like VETH or loopback. Make sure `exec_cmd()` respects `log_outputs` parameter and pass that as `False` when probing for NIC features. Setters intentionally left untouched so failing deliberate action is not washed away.
The first commit is entirely unrelated, but too trivial to justify a separate PR.
> Eliminate some harmless Error: lines from output

- lnst/Recipes/ENRT/BaseTunnelRecipe.py
Includes a network namespace in the test wide description. This is useful for some tests that have multiple devices configured in different namespaces.
For example GeneveOvsNetnsTunnelRecipe:
* before
```
Testwide configuration for recipe GeneveOvsNetnsTunnelRecipe description:
Configured host1.ens5f0np0.ips = [Ip4Address(192.168.80.1/24), Ip6Address(fe80::9a03:9bff:fec6:d2a0/64)]
Configured host2.ens5f0np0.ips = [Ip4Address(192.168.80.2/24), Ip6Address(fe80::9a03:9bff:fec6:d2a4/64)]
Configured host1.peer_lveth0.ips = [Ip6Address(fe80::b0b5:e3ff:fe66:2178/64), Ip4Address(172.16.10.1/32), Ip6Address(fc00:a::1/128)]
Configured host2.peer_lveth0.ips = [Ip6Address(fe80::2c3d:18ff:fecb:c72f/64), Ip4Address(172.16.20.1/32), Ip6Address(fc00:b::1/128)]
Configured host1.peer_lveth0.ips = …
```
> Recipes/ENRT/BaseTunnelRecipe.py: print device namespace

- lnst/Tests/CPUStatMonitor.py
Since the only lines processed by the CPUStatMonitor need to start with 'cpu' string, there's no need to save the whole content of the file.
This also resolve issues caused by https://issues.redhat.com/browse/RHEL-114221
J:11701353
@olichtne
> Tests/CPUStatMonitor.py: save only relevant lines from /cpu/stat
